name: CD - Deploy to Azure

on:
  workflow_run:
    workflows: ["CI - Build and Push Docker"]
    types:
      - completed
permissions:
  id-token: write
  contents: read

jobs:
  deploy-staging:
    runs-on: windows-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        auth-type: service-principal

    - name: Deploy to Azure App Service (Staging)
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.APP_SERVICE_NAME }}
        images: ${{ secrets.ACR_NAME }}.azurecr.io/myapp1:latest

  wait-for-approval:
    needs: deploy-staging
    runs-on: windows-latest
    environment:
      name: production
      url: https://github.com/${{ github.repository }}/actions
    steps:
    - name: Await Manual Approval
      run: echo "Waiting for manual approval..."

  deploy-production:
    needs: wait-for-approval
    runs-on: windows-latest

    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        auth-type: service-principal

    - name: Deploy to Azure App Service (Production)
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.APP_SERVICE_NAME }}
        images: ${{ secrets.ACR_NAME }}.azurecr.io/myapp1:latest

